"""empty message

Revision ID: fbe2c0d11a1b
Revises: 
Create Date: 2023-01-30 22:39:24.979461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe2c0d11a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('keyword_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_table('Topic',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['Keyword.keyword_id'], ),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('Analysis',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('average_view', sa.Integer(), nullable=False),
    sa.Column('max_view', sa.Integer(), nullable=False),
    sa.Column('lastest_updatetime', sa.DateTime(), nullable=False),
    sa.Column('top5links', sa.String(), nullable=False),
    sa.Column('avg_video_length', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['Topic.topic_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Analysis')
    op.drop_table('Topic')
    op.drop_table('Keyword')
    # ### end Alembic commands ###
